// <auto-generated />
using System;
using FlowboardAPI.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowboardAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619013435_AddIamTablesToSharedDbContext")]
    partial class AddIamTablesToSharedDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FlowboardAPI.Attendance.Domain.Model.Aggregates.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendance_record");

                    b.ToTable("attendance_record");
                });

            modelBuilder.Entity("FlowboardAPI.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<bool>("TemporaryPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("temporary_password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FlowboardAPI.Requests.Domain.Model.Aggregates.RequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_request_records");

                    b.ToTable("request_records");
                });

            modelBuilder.Entity("FlowboardAPI.Attendance.Domain.Model.Aggregates.AttendanceRecord", b =>
                {
                    b.OwnsOne("FlowboardAPI.Attendance.Domain.Model.ValueObjects.BiometricId", "BiometricId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_attendance_record");

                            b1.ToTable("attendance_record");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_attendance_record_attendance_record_id");
                        });

                    b.Navigation("BiometricId")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowboardAPI.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("FlowboardAPI.Iam.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("FlowboardAPI.Requests.Domain.Model.Aggregates.RequestRecord", b =>
                {
                    b.OwnsOne("FlowboardAPI.Requests.Domain.Model.ValueObjects.Evidence", "Evidence", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("DocumentUrl")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("document_url");

                            b1.HasKey("Id")
                                .HasName("pk_request_records");

                            b1.ToTable("request_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_request_records_request_records_id");
                        });

                    b.OwnsOne("FlowboardAPI.Requests.Domain.Model.ValueObjects.Justification", "Justification", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("reason");

                            b1.HasKey("Id")
                                .HasName("pk_request_records");

                            b1.ToTable("request_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_request_records_request_records_id");
                        });

                    b.OwnsOne("FlowboardAPI.Requests.Domain.Model.ValueObjects.RequestPeriod", "Period", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("end_date");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("start_date");

                            b1.Property<int>("TotalDays")
                                .HasColumnType("int")
                                .HasColumnName("total_days");

                            b1.HasKey("Id")
                                .HasName("pk_request_records");

                            b1.ToTable("request_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_request_records_request_records_id");
                        });

                    b.OwnsOne("FlowboardAPI.Requests.Domain.Model.ValueObjects.RequestTimeFrame", "TimeFrame", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("date");

                            b1.Property<TimeSpan?>("EndTime")
                                .HasColumnType("time(6)")
                                .HasColumnName("end_time");

                            b1.Property<TimeSpan?>("StartTime")
                                .HasColumnType("time(6)")
                                .HasColumnName("start_time");

                            b1.Property<int>("TotalHours")
                                .HasColumnType("int")
                                .HasColumnName("total_hours");

                            b1.HasKey("Id")
                                .HasName("pk_request_records");

                            b1.ToTable("request_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_request_records_request_records_id");
                        });

                    b.OwnsOne("FlowboardAPI.Requests.Domain.Model.ValueObjects.ReviewDetails", "ReviewDetails", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("RejectionReason")
                                .HasColumnType("longtext")
                                .HasColumnName("rejection_reason");

                            b1.Property<DateTime?>("ReviewedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("reviewed_at");

                            b1.Property<int?>("ReviewerId")
                                .HasColumnType("int")
                                .HasColumnName("reviewer_id");

                            b1.HasKey("Id")
                                .HasName("pk_request_records");

                            b1.ToTable("request_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_request_records_request_records_id");
                        });

                    b.Navigation("Evidence")
                        .IsRequired();

                    b.Navigation("Justification")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("ReviewDetails")
                        .IsRequired();

                    b.Navigation("TimeFrame")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
